### ISSUE TITLE
`display_side_effects` management command could have better error on no docstring

### ISSUE THREAD

**Issue by djm** [yunojuno/django-side-effects#32]
When running `python manage.py display_side_effects` against a codebase with a side-effect that does not have a docstring defined - it errors hard with a very hard to grok error message.

``` 
File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/side_effects/management/commands/display_side_effects.py", line 28, in <dictcomp>
    label: sorted(handlers, key=handler_sort_key)
TypeError: '<' not supported between instances of 'NoneType' and 'list'
task: Failed to run task "freeze-snapshots": exit status 1
```

**Comment by zemgin** [comment]
Full stack trace
```
Traceback (most recent call last):
  File "/Users/[..snip...]/platform/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/[..snip...]/platform/yunojuno/apps/core/management/commands/freeze_snapshots.py", line 25, in handle
    self.call_command("freeze_side_effects", "side_effects.txt")
  File "/Users/[..snip...]/platform/yunojuno/apps/core/management/commands/freeze_snapshots.py", line 15, in call_command
    base_call_command(
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/project_checks/management/commands/base.py", line 107, in handle
    new_lines = self.get_content(*args, **options)
  File "/Users/[..snip...]/platform/yunojuno/apps/core/management/commands/freeze_side_effects.py", line 16, in get_content
    call_command("display_side_effects", stdout=stdout, sorted=True)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/side_effects/management/commands/display_side_effects.py", line 98, in handle
    events = sort_events(
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/side_effects/management/commands/display_side_effects.py", line 27, in sort_events
    return {
  File "/Users/[..snip...]/platform/.venv/lib/python3.10/site-packages/side_effects/management/commands/display_side_effects.py", line 28, in <dictcomp>
    label: sorted(handlers, key=handler_sort_key)
TypeError: '<' not supported between instances of 'NoneType' and 'list'
task: Failed to run task "freeze-snapshots": exit status 1
```

**Comment by hugorodgerbrown** [comment]
This is a bug in the `--sorted` option. The command itself handles functions missing docstrings, but if you try and sort the output it blows up.
